language: "perl"
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - cpanm DBD::Pg

install:
  - true

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: "./postgresqltuner.pl --host=localhost --user=postgres --database=travis_ci_test --password=''"

notifications:
  recipients:
    - julien-postgresqltunertravis@francoz.net
  email:
    on_success: change
    on_failure: always
